In [3]:
import os
import pandas as pd
import yfinance as yf

In [4]:
data = yf.download("USDNGN=X", start="2015-01-01", end="2026-07-24")

[*********************100%***********************]  1 of 1 completed

In [5]:
data.columns = data.columns.droplevel(1)

In [6]:
data.sample(7)

Price             Close         High          Low         Open  Volume
Date
2021-07-28   411.000000   411.010010   411.000000   411.000000       0
2020-08-27   385.519989   386.549988   384.506470   385.519989       0
2019-08-06   362.000000   362.250000   361.989990   362.000000       0
2015-08-24   196.440002   195.800003   194.059998   194.889999       0
2023-04-12   463.000000   462.000000   459.829987   459.829987       0
2025-03-13  1531.500000  1556.920044  1531.500000  1531.500000       0
2021-01-12   374.000000   394.897186   379.750000   380.700012       0

In [7]:
def fetch_forex_data(ticker="USDNGN=X", start_date="2015-01-01", end_date="2026-07-24"):
    """
    Fetches forex data from Yahoo Finance for a given ticker and date range.

    Parameters:
    ticker (str): The ticker symbol for the forex pair (default is "USDNGN=X").
    start_date (str): The start date for the data in "YYYY-MM-DD" format (default is "2015-01-01").
    end_date (str): The end date for the data in "YYYY-MM-DD" format (default is "2026-07-24").

    Returns:
    pd.DataFrame: A DataFrame containing the forex data.
    """
    print(f"Initializing data download for {ticker}...")
    print(f"Window: From {start_date} to {end_date}")

    data = yf.download(ticker, start=start_date, end=end_date)

    if data.empty:
        raise ValueError(
            f"No data retrieved for ticker {ticker}. Verify connection or ticker symbol.")

    missing_vals = data['Close'].isnull().sum()
    print(f"Missing values in 'Close' price: {missing_vals}")

    print(f"Successfully downloaded {len(data)} rows.")
    return data


def save_data(df, directory="../data/raw", filename="raw_usd_ngn.csv"):
    """
    Saves the dataframe to a local directory.
    """
    if not os.path.exists(directory):
        os.makedirs(directory)
        print(f"Created directory: {directory}/")

    filepath = os.path.join(directory, filename)
    df.to_csv(filepath)
    print(f"Data saved successfully to: {filepath}")


if __name__ == "__main__":
    try:
        # Fetch data from 2015 up to the current date in July 2026
        df_fx = fetch_forex_data(
            ticker="USDNGN=X",
            start_date="2015-01-01",
            end_date="2026-07-24"
        )

        df_fx.columns = df_fx.columns.droplevel(
            1)  # Drop the multi-level column index

        # Inspect the first few rows
        print("\nSnapshot of the data:")
        print(df_fx.head())

        # Save to disk
        save_data(df_fx)

    except Exception as e:
        print(f"An error occurred: {e}")

[*********************100%***********************]  1 of 1 completed

Initializing data download for USDNGN=X...
Window: From 2015-01-01 to 2026-07-24
Missing values in 'Close' price: Ticker
USDNGN=X    0
dtype: int64
Successfully downloaded 3009 rows.

Snapshot of the data:
Price            Close        High         Low        Open  Volume
Date
2015-01-01  182.300003  181.380005  181.380005  181.380005       0
2015-01-02  181.380005  182.899994  181.009995  181.869995       0
2015-01-05  182.699997  183.399994  181.500000  182.350006       0
2015-01-06  183.199997  181.949997  180.979996  180.979996       0
2015-01-07  183.600006  182.279999  181.350006  182.279999       0
Data saved successfully to: ../data/raw\raw_usd_ngn.csv

In [8]:
fetch_forex_data()

[*********************100%***********************]  1 of 1 completed

Initializing data download for USDNGN=X...
Window: From 2015-01-01 to 2026-07-24
Missing values in 'Close' price: Ticker
USDNGN=X    0
dtype: int64
Successfully downloaded 3009 rows.

Price             Close         High          Low         Open   Volume
Ticker         USDNGN=X     USDNGN=X     USDNGN=X     USDNGN=X USDNGN=X
Date
2015-01-01   182.300003   181.380005   181.380005   181.380005        0
2015-01-02   181.380005   182.899994   181.009995   181.869995        0
2015-01-05   182.699997   183.399994   181.500000   182.350006        0
2015-01-06   183.199997   181.949997   180.979996   180.979996        0
2015-01-07   183.600006   182.279999   181.350006   182.279999        0
...                 ...          ...          ...          ...      ...
2026-07-20  1379.140015  1380.359985  1378.270020  1379.140015        0
2026-07-21  1379.439941  1381.140015  1377.939941  1379.439941        0
2026-07-22  1379.910034  1380.250000  1372.579956  1379.660034        0
2026-07-23  1371.339966  1372.729980  1366.489990  1371.339966        0
2026-07-24  1371.109985  1371.189941  1365.119995  1371.060059        0

[3009 rows x 5 columns]

In [9]:
save_data(df_fx)

Data saved successfully to: ../data/raw\raw_usd_ngn.csv

In [10]:
df_fx

Price             Close         High          Low         Open  Volume
Date
2015-01-01   182.300003   181.380005   181.380005   181.380005       0
2015-01-02   181.380005   182.899994   181.009995   181.869995       0
2015-01-05   182.699997   183.399994   181.500000   182.350006       0
2015-01-06   183.199997   181.949997   180.979996   180.979996       0
2015-01-07   183.600006   182.279999   181.350006   182.279999       0
...                 ...          ...          ...          ...     ...
2026-07-20  1379.140015  1380.359985  1378.270020  1379.140015       0
2026-07-21  1379.439941  1381.140015  1377.939941  1379.439941       0
2026-07-22  1379.910034  1380.250000  1372.579956  1379.660034       0
2026-07-23  1371.339966  1372.729980  1366.489990  1371.339966       0
2026-07-24  1371.109985  1371.189941  1365.119995  1371.060059       0

[3009 rows x 5 columns]